
export const dataPortfolio = [
    {
        id: 1,
        title: "Web Pro",
        image: "/image-1.jpg",
        urlGithub: "#!",
        urlDemo: "#!",
    },
    {
        id: 2,
        title: "Desarrollo Web Ágil",
        image: "/image-2.jpg",
        description: "Aplicación de gestión de tareas desarrollada con React y Node.js. Permite crear, editar y eliminar tareas de manera eficiente.",
        urlGithub: "#!",
        urlDemo: "#!",
    },
    {
        id: 3,
        title: "Spring Boot",
        image: "/image-3.jpg",
        description: "Aplicación de gestión de tareas desarrollada con Spring Boot y React. Permite crear, editar y eliminar tareas de manera eficiente.",
        urlGithub: "#!",
        urlDemo: "#!",
    },
    {
        id: 4,
        title: "MASTER SCHEDULER",
        image: "/image-4.png",
        description: "Sistema de ventas desarrollado con C# y React. Permite gestionar productos, clientes y ventas de manera eficiente.",
        urlGithub: "https://github.com/JHOEL-G/SISTEM_DE_VENTAS",
        urlDemo: "https://sistem-de-ventas.vercel.app/",
    },
    {
        id: 5,
        title: "TIENDA ONLINE",
        image: "/img5.png",
        description: "Tienda online desarrollada con React y Node.js. Permite gestionar productos, clientes y ventas de manera eficiente.",
        urlGithub: "https://github.com/JHOEL-G/tienda-online",
        urlDemo: "https://tienda-online-n5e0.onrender.com/",
    },
    {
        id: 6,
        title: "INTELIGENCIA ARTIFICIAL",
        image: "/img6.png",
        descripcion: '',
        urlGithub: "https://github.com/JHOEL-G/Pagina",
        urlDemo: "https://masterenginer.netlify.app/",
    },
];
